version: "3.9"
services:
  database:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: sample
      POSTGRES_USER: sample
      POSTGRES_DB: sample
    ports:
      - "5432:5432"

  backend:
    image: client
    build:
      context: .
      dockerfile: \backend\Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - database
    environment:
      - SERVER_PORT=8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database/sample
      - SPRING_DATASOURCE_USERNAME=sample
      - SPRING_DATASOURCE_PASSWORD=sample